# DataFrame Analytics

Load the full registry into a pandas DataFrame and run analytics.

Requires the analytics extra:

```bash
pip install anchorregistry[analytics]
```

> These examples run against Sepolia testnet (`network="sepolia"`).
> To run against Base mainnet: replace `configure(network="sepolia")` with `configure(network="base")`.
> All function calls, record structures, and output shapes are identical across networks.

In [2]:
# Cell 1 — setup
from anchorregistry import configure, get_all, to_dataframe
import pandas as pd

configure(network="sepolia", rpc_url="https://ethereum-sepolia-rpc.publicnode.com")

In [3]:
# Cell 2 — load full registry into DataFrame
df = to_dataframe(get_all())
print(f"Shape: {df.shape}")
df.dtypes

Shape: (12, 71)

ar_id                    str
registered              bool
artifact_type_index    int64
artifact_type_name       str
tx                       str
                       ...
data_data_version        str
data_format              str
data_row_count           str
data_schema_url          str
data_url                 str
Length: 71, dtype: object

In [4]:
# Cell 3 — filter by artifact type
# Type-specific data fields are flattened as {type_name}_{field_name}
# e.g. RESEARCH fields -> research_doi, research_institution, research_co_authors, research_url
research_df = df[df.artifact_type_name == "RESEARCH"]
cols = ["ar_id", "title", "research_doi", "research_institution", "research_url"]
research_df[[c for c in cols if c in research_df.columns]]

,ar_id,title,research_doi,research_institution,research_url
9,AR-2026-K6NpOk1,test research,,,https://anchorregistry.ai/
10,AR-2026-D5bqN06,test research,,,https://anchorregistry.ai/

In [5]:
# Cell 4 — filter by registrant
registrant_df = df[df.registrant == "0xc7a7afde1177fbf0bb265ea5a616d1b8d7ed8c44"]
registrant_df[["ar_id", "artifact_type_name", "title"]]

              ar_id artifact_type_name                title
0       AR-SMK-CODE               CODE  Smoke Test Artifact
1      AR-SMK-MEDIA              MEDIA  Smoke Test Artifact
2       AR-SMK-TEXT               TEXT  Smoke Test Artifact
3     AR-SMK-REPORT             REPORT  Smoke Test Artifact
4       AR-SMK-NOTE               NOTE  Smoke Test Artifact
5    AR-SMK-RECEIPT            RECEIPT  Smoke Test Artifact
6      AR-SMK-OTHER              OTHER  Smoke Test Artifact
7    AR-SMK-WEBSITE            WEBSITE  Smoke Test Artifact
8    AR-SMK-RETRACT         RETRACTION  Smoke Test Artifact
9   AR-2026-K6NpOk1           RESEARCH        test research
10  AR-2026-D5bqN06           RESEARCH        test research
11  AR-2026-p12z0e1               DATA            test data

In [6]:
# Cell 5 — group by artifact type
df.groupby("artifact_type_name").size().sort_values(ascending=False)

artifact_type_name
RESEARCH      2
CODE          1
DATA          1
MEDIA         1
NOTE          1
OTHER         1
RECEIPT       1
REPORT        1
RETRACTION    1
TEXT          1
WEBSITE       1
dtype: int64

In [7]:
# Cell 6 — tree analysis
df.groupby("tree_id").size().sort_values(ascending=False)

tree_id
                                                                    9
7ec2e3117b73605f7eb339fa9d550d08eec94cc5003a8efe61b9075eb88fa7bb    2
8c0565176f397726ddbad2131e7d90eb03f778ed488856951ea4dd79c8510444    1
dtype: int64